import { ReactNode, Suspense } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientLayout from "app/ClientLayout";
import { StoreWrapper } from "store/storeWrapper";
import { ProgressBar } from "common/components";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Inctagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <StoreWrapper>
          <Suspense fallback={<ProgressBar />}>
            <ClientLayout>{children}</ClientLayout>
          </Suspense>
        </StoreWrapper>
      </body>
    </html>
  );
}
