import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "common/components";
import { Inter } from "next/font/google";
import s from "./page.module.css";
import { StoreWrapper } from "store/storeWrapper";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Inctagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <StoreWrapper>
          <Header />
          <main className={s.main}>{children}</main>
        </StoreWrapper>
      </body>
    </html>
  );
}
