import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "common/components/Header/Header";
import { Inter } from "next/font/google";
import Navbar from "../common/components/Navbar/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Inctagram",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.variable}`}>
    <Header />
    <div style={{ display: "flex" }}>
      <Navbar />
      <main>{children}</main>
    </div>
    </body>
    </html>
  );
}
